build:
    requirements: {}
dependencies:
    counties: census.gov-index-counties
sources:
    food_affordability:
        comment: null
        conversion: null
        dd_url: null
        description: 'Food Affordability: average cost of a market basket of nutritious
            food items relative to income '
        encoding: null
        file: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec: {}
        url: http://www.cdph.ca.gov/programs/Documents/Food_afford_cdp_co_region_ca4-14-13.xls
        urlfiletype: null
    healthy_food:
        comment: null
        conversion: null
        dd_url: null
        description: 'Access to healthy foods: retail food environment index  '
        encoding: null
        file: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec: {}
        url: http://www.cdph.ca.gov/programs/Documents/HCI_RetailFoodEnvironment_75_CA_CO_RE_PL_CT_11-15-13.xls
        urlfiletype: null
    high_school_ed:
        comment: null
        conversion: null
        dd_url: null
        description: 'High School or Greater Educational Attainment in the Population
            Aged 25 Years and Older    '
        encoding: null
        file: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec: {}
        url: http://www.cdph.ca.gov/programs/Documents/ed_attain_ge_hs_output04-14-13.zip
        urlfiletype: null
    income_inequality:
        comment: null
        conversion: null
        dd_url: null
        description: 'Income Inequality: Household income relative to the number of
            households '
        encoding: null
        file: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec: {}
        url: http://www.cdph.ca.gov/programs/Documents/gini_place_county_region_st3-26-14.xlsx
        urlfiletype: null
    open_space:
        comment: null
        conversion: null
        dd_url: null
        description: 'Access to Parks: Percent of residents within 1/2 mile of a park,
            beach, or open space'
        encoding: null
        file: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec: {}
        url: http://www.cdph.ca.gov/programs/Documents/ParkBeachOpen10_output4-12-13.zip
        urlfiletype: null
    unemployment:
        comment: null
        conversion: null
        dd_url: null
        description: Unemployment Rate
        encoding: null
        file: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec: {}
        url: http://www.cdph.ca.gov/programs/Documents/HCI_Unemployment_290_CA_RE_CO_CD_PL_CT-5-22-14.zip
        urlfiletype: null
views: {}
