build: {}
dependencies: {}
sources:
    Community_Report_Card_Example10-30-14:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/Community_Report_Card_Example10-30-14.xlsx
    Community_Report_Card_for_HCI_website_Excel_Blank_Template10-17-14:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/Community_Report_Card_for_HCI_website_Excel_Blank_Template10-17-14.xlsx
    Food_afford_cdp_co_region_ca4-14-13:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/Food_afford_cdp_co_region_ca4-14-13.xls
    HCIShapeFiles:
        description: shp
        url: http://www.cdph.ca.gov/programs/Documents/HCIShapeFiles.zip
    HCI_ACS_CHAS_RaceIncome_HousingCostBurden_CT_PL_CO-O-S-7-30-14:
        description: Orange-Sutter Counties
        url: http://www.cdph.ca.gov/programs/Documents/HCI_ACS_CHAS_RaceIncome_HousingCostBurden_CT_PL_CO-O-S-7-30-14.zip
    HCI_ACS_CHAS_RaceIncome_HousingCostBurden_CT_PL_CO-T-Y-7-30-14:
        description: Tehama-Yuba Counties
        url: http://www.cdph.ca.gov/programs/Documents/HCI_ACS_CHAS_RaceIncome_HousingCostBurden_CT_PL_CO-T-Y-7-30-14.zip
    HCI_ACS_CHAS_RaceIncome_HousingCostBurden_CT_PL_CO_RE_ST-A-N-7-30-14:
        description: Alameda-Nevada Counties, State, Regions
        url: http://www.cdph.ca.gov/programs/Documents/HCI_ACS_CHAS_RaceIncome_HousingCostBurden_CT_PL_CO_RE_ST-A-N-7-30-14.zip
    HCI_AbuseNeglectChildren_741_CT_PL_CO_RE_CA-24-4-15:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/HCI_AbuseNeglectChildren_741_CT_PL_CO_RE_CA-24-4-15.xlsx
    HCI_AlcoholOutletsQ_774_CA_RE_CO_CD_PL_CT-A-N-5-16-14:
        description: None
        url: http://www.cdph.ca.gov/programs/Documents/HCI_AlcoholOutletsQ_774_CA_RE_CO_CD_PL_CT-A-N-5-16-14.zip
    HCI_AlcoholOutletsQ_774_CO_CD_PL_CT-O-Y-5-16-14:
        description: None
        url: http://www.cdph.ca.gov/programs/Documents/HCI_AlcoholOutletsQ_774_CO_CD_PL_CT-O-Y-5-16-14.zip
    HCI_CHAS_IncomeCrowding_PL_CO_RE_ST:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/HCI_CHAS_IncomeCrowding_PL_CO_RE_ST.xls
    HCI_DrinkingWater_CA_RE_CO_CD_PL_CT-A-N-6-19-14:
        description: None
        url: http://www.cdph.ca.gov/programs/Documents/HCI_DrinkingWater_CA_RE_CO_CD_PL_CT-A-N-6-19-14.zip
    HCI_DrinkingWater_CA_RE_CO_CD_PL_CT-O-Y-6-19-14:
        description: Orange-Yuba Counties
        url: http://www.cdph.ca.gov/programs/Documents/HCI_DrinkingWater_CA_RE_CO_CD_PL_CT-O-Y-6-19-14.zip
    HCI_HouseholdType_746_CARECOCDPLCT_Alameda-Monterey_24APR15:
        description: None
        url: http://www.cdph.ca.gov/programs/Documents/HCI_HouseholdType_746_CARECOCDPLCT_Alameda-Monterey_24APR15.zip
    HCI_HouseholdType_746_CT_Napa-Yuba_24APR15:
        description: Census tracts (Napa-Yuba)
        url: http://www.cdph.ca.gov/programs/Documents/HCI_HouseholdType_746_CT_Napa-Yuba_24APR15.zip
    HCI_JobHouseRatio_PL-MS-CO-768-4-24-15:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/HCI_JobHouseRatio_PL-MS-CO-768-4-24-15.xlsx
    HCI_JobsMatch_PL-MS-CO_769_4-24-15:
        description: None
        url: http://www.cdph.ca.gov/programs/Documents/HCI_JobsMatch_PL-MS-CO_769_4-24-15.xlsx
    HCI_Living_Wage_770_PL_CO_RE_CA_9-29-13:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/HCI_Living_Wage_770_PL_CO_RE_CA_9-29-13.xls
    HCI_MilesByOccurrence_39_CA_CO_PL_RE_10-3-13:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/HCI_MilesByOccurrence_39_CA_CO_PL_RE_10-3-13.xls
    HCI_NeighborhoodChange_772_CARECOCDPLCT_Alameda-Lake_24APR15:
        description: State, Counties, Regions, County Divisions, Census tracts (Alameda-Lake)
        url: http://www.cdph.ca.gov/programs/Documents/HCI_NeighborhoodChange_772_CARECOCDPLCT_Alameda-Lake_24APR15.zip
    HCI_NeighborhoodChange_772_CT_Lassen-Sacramento_24APR15:
        description: Census tracts (Lassen-Sacramento)
        url: http://www.cdph.ca.gov/programs/Documents/HCI_NeighborhoodChange_772_CT_Lassen-Sacramento_24APR15.zip
    HCI_NeighborhoodChange_772_CT_SanBenito-Yuba_24APR15:
        description: Census tracts (San Benito-Yuba)
        url: http://www.cdph.ca.gov/programs/Documents/HCI_NeighborhoodChange_772_CT_SanBenito-Yuba_24APR15.zip
    HCI_PovertyRate_754_CT_PL_CO_RE_CA_1-22-14:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/HCI_PovertyRate_754_CT_PL_CO_RE_CA_1-22-14.zip
    HCI_RegisteredVoters_653_CA_CO_RE_PL_CT_5-1-14:
        description: None
        url: http://www.cdph.ca.gov/programs/Documents/HCI_RegisteredVoters_653_CA_CO_RE_PL_CT_5-1-14.zip
    HCI_RetailFoodEnvironment_75_CA_CO_RE_PL_CT_11-15-13:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/HCI_RetailFoodEnvironment_75_CA_CO_RE_PL_CT_11-15-13.xls
    HCI_RoadTrafficInjuries_753_CT_PL_CO_12-17-13_O-Y:
        description: None
        url: http://www.cdph.ca.gov/programs/Documents/HCI_RoadTrafficInjuries_753_CT_PL_CO_12-17-13_O-Y.zip
    HCI_RoadTrafficInjuries_753_CT_PL_CO_RE_R4_CA-12-17-13_A-N:
        description: Alameda-Nevada Counties, State, Regions
        url: http://www.cdph.ca.gov/programs/Documents/HCI_RoadTrafficInjuries_753_CT_PL_CO_RE_R4_CA-12-17-13_A-N.zip
    HCI_Transportation2Work_42_CT_PL_CO_RE_ST_12-12-13-revised:
        description: None
        url: http://www.cdph.ca.gov/programs/Documents/HCI_Transportation2Work_42_CT_PL_CO_RE_ST_12-12-13-revised.zip
    HCI_Unemployment_290_CA_RE_CO_CD_PL_CT-5-22-14:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/HCI_Unemployment_290_CA_RE_CO_CD_PL_CT-5-22-14.zip
    HCI_Walk_Bicycle_778_PL_CO_RE_CA-3-26-14:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/HCI_Walk_Bicycle_778_PL_CO_RE_CA-3-26-14.xlsx
    Housing_Cost_Burden_ACS_106:
        description: sas
        url: http://www.cdph.ca.gov/programs/Documents/Housing_Cost_Burden_ACS_106.zip
    Housing_Cost_Burden_CHAS_106:
        description: sas
        url: http://www.cdph.ca.gov/programs/Documents/Housing_Cost_Burden_CHAS_106.zip
    Housing_Crowding_137:
        description: sas
        url: http://www.cdph.ca.gov/programs/Documents/Housing_Crowding_137.zip
    PM25_zcta_place_co_region_ca4-14-13:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/PM25_zcta_place_co_region_ca4-14-13.xls
    ParkBeachOpen10_output4-12-13:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/ParkBeachOpen10_output4-12-13.zip
    PublicTransitAccess:
        description: sas
        url: http://www.cdph.ca.gov/programs/Documents/PublicTransitAccess.zip
    RailFerryBus10_MTC_Output_11-15-13:
        description: Bay Area
        url: http://www.cdph.ca.gov/programs/Documents/RailFerryBus10_MTC_Output_11-15-13.xls
    RailFerryBus10_SACOG_Output-11-26-13:
        description: Sacramento County Area
        url: http://www.cdph.ca.gov/programs/Documents/RailFerryBus10_SACOG_Output-11-26-13.xls
    RailFerryBus10_SANDAG_Output8-29-13:
        description: None
        url: http://www.cdph.ca.gov/programs/Documents/RailFerryBus10_SANDAG_Output8-29-13.xls
    RailFerryBus10_SCAG_Output9-5-13:
        description: Southern California
        url: http://www.cdph.ca.gov/programs/Documents/RailFerryBus10_SCAG_Output9-5-13.xls
    RoadTrafficInjuries:
        description: sas
        url: http://www.cdph.ca.gov/programs/Documents/RoadTrafficInjuries.zip
    UCR_city_county_region2006_2010_04-14-13:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/UCR_city_county_region2006_2010_04-14-13.xls
    ed_attain_ge_hs_output04-14-13:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/ed_attain_ge_hs_output04-14-13.zip
    gini_place_county_region_st3-26-14:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/gini_place_county_region_st3-26-14.xlsx
    ozone_zcta_place_co_region_ca4-14-13:
        description: xls
        url: http://www.cdph.ca.gov/programs/Documents/ozone_zcta_place_co_region_ca4-14-13.xls
views: {}
