build: {}
dependencies: {}
extract: {}
sources:
    zips:
        description: Zip code boundary file
        space: California
        time: 2015
        url: http://www.oshpd.ca.gov/HWDD/MSSA/GIS/GIS-Shapefile-ZipCode.zip
views: {}
