build:
    extra_columns:
        all:
            oshpd_id: oshpd_facilities.oshpd_id
            year: oshpd_facilities.year
dependencies: {}
sources:
    edcare:
        comment: null
        conversion: null
        dd_url: null
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_start_line: 3
            header_comment_lines:
            - 0
            header_lines:
            - 1
            - 2
        segment: 8
        space: California
        time: 2014
        title: ED Care
        url: http://ds.civicknowledge.org.s3.amazonaws.com/calqualitycare.org/Public%20Reports%202014Q3.xlsx
    experience:
        comment: null
        conversion: null
        dd_url: null
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_start_line: 3
            header_comment_lines:
            - 0
            header_lines:
            - 1
            - 2
        segment: 1
        space: California
        time: 2014
        title: Patient Experience
        url: http://ds.civicknowledge.org.s3.amazonaws.com/calqualitycare.org/Public%20Reports%202014Q3.xlsx
    heartcond:
        comment: null
        conversion: null
        dd_url: null
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_start_line: 3
            header_comment_lines:
            - 0
            header_lines:
            - 1
            - 2
        segment: 4
        space: California
        time: 2014
        title: Heart Conditions
        url: http://ds.civicknowledge.org.s3.amazonaws.com/calqualitycare.org/Public%20Reports%202014Q3.xlsx
    hospitals:
        comment: null
        conversion: null
        dd_url: null
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_start_line: 3
            header_comment_lines:
            - 0
            header_lines:
            - 1
            - 2
        segment: 10
        space: California
        time: 2014
        title: Hospital Characteristics
        url: http://ds.civicknowledge.org.s3.amazonaws.com/calqualitycare.org/Public%20Reports%202014Q3.xlsx
    lung:
        comment: null
        conversion: null
        dd_url: null
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_start_line: 3
            header_comment_lines:
            - 0
            header_lines:
            - 1
            - 2
        segment: 6
        space: California
        time: 2014
        title: Lung Conditions
        url: http://ds.civicknowledge.org.s3.amazonaws.com/calqualitycare.org/Public%20Reports%202014Q3.xlsx
    measures:
        comment: null
        conversion: null
        dd_url: null
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_start_line: 3
            header_comment_lines:
            - 0
            header_lines:
            - 1
            - 2
        segment: 9
        space: California
        time: 2014
        title: Measure Characteristics
        url: http://ds.civicknowledge.org.s3.amazonaws.com/calqualitycare.org/Public%20Reports%202014Q3.xlsx
    motherbaby:
        comment: null
        conversion: null
        dd_url: null
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_start_line: 3
            header_comment_lines:
            - 0
            header_lines:
            - 1
            - 2
        segment: 5
        space: California
        time: 2014
        title: Mother and Baby
        url: http://ds.civicknowledge.org.s3.amazonaws.com/calqualitycare.org/Public%20Reports%202014Q3.xlsx
    other:
        comment: null
        conversion: null
        dd_url: null
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_start_line: 3
            header_comment_lines:
            - 0
            header_lines:
            - 1
            - 2
        segment: 7
        space: California
        time: 2014
        title: Other Conditions
        url: http://ds.civicknowledge.org.s3.amazonaws.com/calqualitycare.org/Public%20Reports%202014Q3.xlsx
    perf_sum:
        comment: null
        conversion: null
        dd_url: null
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_start_line: 3
            header_comment_lines:
            - 0
            header_lines:
            - 1
            - 2
        segment: 0
        space: California
        time: 2014
        title: Performance Summary
        url: http://ds.civicknowledge.org.s3.amazonaws.com/calqualitycare.org/Public%20Reports%202014Q3.xlsx
    readmissions:
        comment: null
        conversion: null
        dd_url: null
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_start_line: 3
            header_comment_lines:
            - 0
            header_lines:
            - 1
            - 2
        segment: 2
        space: California
        time: 2014
        title: Readmissions
        url: http://ds.civicknowledge.org.s3.amazonaws.com/calqualitycare.org/Public%20Reports%202014Q3.xlsx
    safety:
        comment: null
        conversion: null
        dd_url: null
        file: null
        filetype: null
        foreign_key: null
        is_loadable: null
        row_data: null
        row_spec:
            data_start_line: 3
            header_comment_lines:
            - 0
            header_lines:
            - 1
            - 2
        segment: 3
        space: California
        time: 2014
        title: Patient Safety
        url: http://ds.civicknowledge.org.s3.amazonaws.com/calqualitycare.org/Public%20Reports%202014Q3.xlsx
views: {}
