build: {}
dependencies: {}
extract: {}
sources:
    dental:
        description: Dental Designation
        grain: entity
        space: california
        time: 201407
        url: http://www.oshpd.ca.gov/HWDD/MSSA/GIS/HPSADentalv201407.zip
    mental:
        description: Mental Health Designation
        grain: entity
        space: california
        time: 201407
        url: http://www.oshpd.ca.gov/HWDD/MSSA/GIS/HPSAMentalHealthv201407.zip
    nurse:
        description: Registered Nurse Shortage Areas
        grain: entity
        space: california
        time: 201407
        url: http://www.oshpd.ca.gov/HWDD/MSSA/GIS/RNSAv13.zip
    primarycare:
        description: Primary Care Professional Designation
        grain: entity
        space: california
        time: 201407
        url: http://www.oshpd.ca.gov/HWDD/MSSA/GIS/PCSAv13.zip
    primarypro:
        description: Primary Care Professional Designation
        grain: entity
        space: california
        time: 201407
        url: http://www.oshpd.ca.gov/HWDD/MSSA/GIS/HPSAPrimaryCarev201407.zip
views: {}
