build: {}
dependencies: {}
sources:
    facility_cross:
        description: Crosswalk between OSHPD and CDPH health care facility numbers
        space: California
        time: 2015
        url: https://chhs.data.ca.gov/api/views/tthg-z4mf/rows.csv
    meta:
        filetype: socrata/json
        is_loadable: false
        url: https://chhs.data.ca.gov/api/views/tthg-z4mf
views: {}
