build:
    requirements:
        xlrd: xlrd
dependencies: {}
sources:
    Hosp08_util_data_FINAL:
        description: Hospital Utilization
        row_spec:
            data_end_line: null
            data_start_line: 4
            header_comment_lines: []
            header_lines:
            - 0
            - 3
        segment: 2
        table: hosp_util
        url: http://www.oshpd.ca.gov/hid/Products/Hospitals/Utilization/Text_pdf_files/Hospital/Annual_Utilization/Hosp08_util_data_FINAL.xls
    Hosp09_util_data_Final:
        description: Hospital Utilization
        row_spec:
            data_end_line: null
            data_start_line: 4
            header_comment_lines: []
            header_lines:
            - 0
            - 3
        segment: 2
        table: hosp_util
        url: http://www.oshpd.ca.gov/hid/Products/Hospitals/Utilization/Text_pdf_files/Hospital/Annual_Utilization/Hosp09_util_data_Final.xls
    Hosp10_util_data_FINAL:
        description: Hospital Utilization
        row_spec:
            data_end_line: null
            data_start_line: 4
            header_comment_lines: []
            header_lines:
            - 0
            - 3
        segment: 2
        table: hosp_util
        url: http://www.oshpd.ca.gov/hid/Products/Hospitals/Utilization/Text_pdf_files/Hospital/Annual_Utilization/Hosp10_util_data_FINAL.xlsx
    Hosp11_util_data_Final:
        description: Hospital Utilization
        row_spec:
            data_end_line: null
            data_start_line: 4
            header_comment_lines: []
            header_lines:
            - 0
            - 3
        segment: 2
        table: hosp_util
        url: http://www.oshpd.ca.gov/hid/Products/Hospitals/Utilization/Text_pdf_files/Hospital/Annual_Utilization/Hosp11_util_data_Final.xlsx
    Hosp12_util_data_FINAL:
        description: Hospital Utilization
        row_spec:
            data_end_line: null
            data_start_line: 4
            header_comment_lines: []
            header_lines:
            - 0
            - 3
        segment: 2
        table: hosp_util
        url: http://www.oshpd.ca.gov/hid/Products/Hospitals/Utilization/Text_pdf_files/Hospital/Annual_Utilization/Hosp12_util_data_FINAL.xlsx
    Hosp13_util_data_FINAL:
        description: Hospital Utilization
        row_spec:
            data_end_line: null
            data_start_line: 4
            header_comment_lines: []
            header_lines:
            - 0
            - 3
        segment: 2
        table: hosp_util
        url: http://www.oshpd.ca.gov/hid/Products/Hospitals/Utilization/Text_pdf_files/Hospital/Annual_Utilization/Hosp13_util_data_FINAL.xlsx
views: {}
